# DOCS https://github.com/rvben/rumdl/blob/main/docs/global-settings.md

[global]
line-length = 80
disable = [
  "blanks-around-lists",  # rule of proximity
  "first-line-h1",
]
cache = false  # avoid noisy `.rumdl_cache`

# ------------------------------------------------------------------------------

[ul-style]
style = "dash"  # GitHub default & quicker to type

[ul-indent]
indent = 4  # consistent with .editorconfig

[line-length]
code-blocks = false
reflow = true  # enable auto-formatting

[blanks-around-headings]
lines-below = 0  # rule of proximity

[ol-prefix]
style = "ordered"

[no-inline-html]
allowed-elements = ["a", "img"]  # badges

[emphasis-style]
style = "asterisk"  # better than underscore, since not considered a word-char

[strong-style]
style = "asterisk"

[table-format]
enabled = true  # opt-in rule

[heading-capitalization]
enabled = true  # opt-in rule
style = "sentence_case"
ignore-words = ["nvim", "Obsidian", "Alfred"]

[frontmatter-key-sort]
enabled = true  # opt-in rule

[toc-validation]
enabled = true  # opt-in rule

# ------------------------------------------------------------------------------

# DOCS https://rumdl.dev/code-block-tools/
[code-block-tools]
enabled = true
timeout = 10000  # 10 seconds

[code-block-tools.languages]
python = { format = ["ruff:format"] }
shell = { format = ["shfmt"] }
lua = { format = ["stylua"] }
toml = { format = ["tombi"] }
markdown = { format = ["rumdl"] }
json = { format = ["jq"] }
