# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
# DOCS https://espanso.org/docs/configuration/options/
#───────────────────────────────────────────────────────────────────────────────

search_trigger: OFF
search_shortcut: ""

show_icon: false
show_notifications: true
auto_restart: true

undo_backspace: false # backspace undos expansion
backend: auto
