# yaml-language-server: $schema=https://raw.githubusercontent.com/ajmarkow/espanso-schema-json/master/schemas/Espanso_Config_File_Schema.json
# DOCS https://espanso.org/docs/configuration/options/
#───────────────────────────────────────────────────────────────────────────────

search_trigger: OFF
search_shortcut: ""

show_icon: false
show_notifications: true
auto_restart: true # alternatively via Makefile, but is slower and annoying to sync

undo_backspace: false # backspace undos expansion
backend: Auto
