# yaml-language-server: $schema=https://raw.githubusercontent.com/ajmarkow/espanso-schema-json/master/schemas/Espanso_Config_File_Schema.json
#───────────────────────────────────────────────────────────────────────────────

filter_class: com.mimestream.Mimestream

extra_includes:
  - "../match/_email.yml"
