# yaml-language-server: $schema=../schemas/espanso-appconfig-schema.json
#───────────────────────────────────────────────────────────────────────────────

# https://espanso.org/docs/configuration/app-specific-configurations/
filter_class: "net.highlightsapp.universal"

extra_includes:
  - "../match/_annotation-tags.yml"
