# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────

filter_class: com.apple.TextEdit

extra_includes:
  - ../match/_mail.yml
