# DOCS https://github.com/crate-ci/typos/blob/master/docs/reference.md
#───────────────────────────────────────────────────────────────────────────────

# ignore these files
# INFO (needs glob due to conform.nvim appending stuff for temporary file)
[files]
extend-exclude = ["*.bib"] # too many false positives
