# https://yamllint.readthedocs.io/en/stable/configuration.html#extending-the-default-configuration
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

rules:
  line-length: disable
  document-start: disable
  # Sublime already takes care of that
  trailing-spaces: disable
  new-line-at-end-of-file: disable
