# DOCS https://microsoft.github.io/pyright/#/configuration
[tool.pyright]
venvPath = "."
venv = ".venv"
strict = ["."]
typeCheckingMode = "strict"

[tool.python.analysis]
diagnosticMode = "workspace"

#───────────────────────────────────────────────────────────────────────────────

# DOCS https://beta.ruff.rs/docs/rules/
[tool.ruff]
line-length = 100
exclude = [
	".venv",
	"typings/*.pyi"
]
select = ["ALL"]
ignore = [
	"T201",   # print statements
	"T100",   # "breakpoint()"
	"S311",   # requires cryptographically secure random number generators
	"W",      # pycodestyle warnings are already autofixed by black
	"RET504", # unnecessary assign for return (makes stuff less verbose)
	"ERA001", # commented out code
	"TD",     # allow TODO
	"FIX002", # complain about TODO in general
	"FIX004", # complain about HACK
	"S607",   # shell command without full path
	"S605",   # shell instead of subshell

	# DUPLICATON WITH PYRIGHT
	"F841",   # unused var
	"F401",   # unused import
	"ARG001", # unused arg
	"F821",   # undefined variable
]

[tool.ruff.pydocstyle]
convention = "google" # "google"|"numpy"|"pep257"

#───────────────────────────────────────────────────────────────────────────────
