[lints]
# disabled since duplication with LSP
undefined_variable = "allow"
unused_variable = "allow"
empty_if = "allow"
multiple_statements = "allow"

# changed severity
if_same_then_else = "warn"

#───────────────────────────────────────────────────────────────────────────────

high_cyclomatic_complexity = "warn" # enabled

[config]
high_cyclomatic_complexity = { maximum_complexity = 20 }
