# DOCS https://neovide.dev/config-file.html#available-settings

frame = "buttonless"
no-multigrid = false
title-hidden = true
tabs = false
mouse-cursor-icon = "i-beam"

[font]
normal = ["JetBrainsMonoNL NF", "Menlo"]
size = 24.5

[box-drawing]
mode = "font-glyph"
