# DOCS https://github.com/crate-ci/typos/blob/master/docs/reference.md
#───────────────────────────────────────────────────────────────────────────────

# ignore these files
[files]
extend-exclude = ["spelling.yml", "spelling-german.yml"]

# ignore these words, since they are common in German
[default.extend-words]
als = "als"
ist = "ist"
ein = "ein"
oder = "oder"
vor = "vor"
sie = "sie"
habe = "habe"
alle = "alle"
