# https://github.com/Rigellute/spotify-tui#configuration
# Sample config file

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  enable_text_emphasis: true
  show_loading_indicator: true
  set_window_title: true

  liked_icon: ğŸ’š
  shuffle_icon: ğŸ”€
  repeat_track_icon: ğŸ”‚
  repeat_context_icon: ğŸ”
  playing_icon: â–¶ï¸
  paused_icon: â¸

