# DOCS https://github.com/crate-ci/typos/blob/master/docs/reference.md
#───────────────────────────────────────────────────────────────────────────────

# ignore these words
[default.extend-words]
# keymaps used in the obsidian-vimrc
siz = "siz"
sie = "sie"
vas = "vas"
iy = "iy"
viw = "viw"

# romaji/hiragana
ba = "ba"
myu = "myu"
